# Generated by Django 3.0.3 on 2020-03-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepost_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecolumn',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
