# Generated by Django 3.0.3 on 2020-03-04 20:04

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200304_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={},
        ),
        migrations.AddField(
            model_name='articlepost',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='article/%Y/%m%d'),
        ),
    ]
