# Generated by Django 3.0.3 on 2020-03-05 16:48

import ckeditor.fields
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200304_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='article/'),
        ),
    ]
