# Generated by Django 3.0.3 on 2020-03-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200305_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='total_views',
            new_name='views',
        ),
        migrations.AddField(
            model_name='articlepost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
