# Generated by Django 3.0.3 on 2020-03-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200306_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
