# Generated by Django 3.0.3 on 2020-03-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20200306_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
    ]
